name: Use Personal Container

on:
    workflow_dispatch:

jobs:
  use-container:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tentemarrero/testimage:latest
      #options: --workdir /home/runner/appContainer  # Set the working directory inside the container
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Print current folder
        run: |
          echo "Current folder: ${{ github.workspace }}"
      - name: List folder content
        run: |
          cd ..
          ls -l
          cd ..
          ls -l
          cd ..
          ls -l
